/*
 * Level.java
 * Suraj Rampure
 * 
 * This class is used to create Level objects from text files
 * There are 25 such fils in the folder "levels"
 */

import java.util.*;

public class Level {
	
	// Attributes of Level objects
	int levelNumber;
	int [] numBlocks = new int [10];				// The number of blocks at each y value
	int [][] arrayToMatch = new int [8][10];		// What the user has to recreate
	
	// Constructor method
	public Level (Scanner s) {
		
		// The class accepts a Scanner as the parameter
		// Each of the attributes are generated by reading from the Scanner
		
		levelNumber = Integer.parseInt(s.nextLine());

		String [] loadNums = s.nextLine().split(",");
		
		for (int i = 0; i < 10; i ++) {
			numBlocks[i] = Integer.parseInt(loadNums[i]);
		}
		
		String [][] loadArray = new String [8][10];
		
		for (int x = 0; x < 8; x ++) {
			loadArray[x] = s.nextLine().split(",");
		}
		
		
		for (int x = 0; x < 8; x ++) {
			for (int y = 0; y < 10; y ++) {
				arrayToMatch[x][y] = Integer.parseInt(loadArray[x][y]);
			}
		}
		

	}

	
}